apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1
spec:
  replicas: 3  # Number of instances
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: manhdungnguyen/server1:latest  # Update with your image name
        ports:
        - containerPort: 8080
